<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.mHn0zVB' shared service.

return $this->privates['.service_locator.mHn0zVB'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'App\\Controller\\AjoutController::depot' => ['privates', '.service_locator.ZIsCxOI', 'get_ServiceLocator_ZIsCxOIService.php', true],
    'App\\Controller\\AjoutController::listParten' => ['privates', '.service_locator.eIEYWuf', 'get_ServiceLocator_EIEYWufService.php', true],
    'App\\Controller\\AjoutController::partuser' => ['privates', '.service_locator.H3qnu8f', 'get_ServiceLocator_H3qnu8fService.php', true],
    'App\\Controller\\AjoutController::userBloquer' => ['privates', '.service_locator.U2OyWts', 'get_ServiceLocator_U2OyWtsService.php', true],
    'App\\Controller\\UserController::new' => ['privates', '.service_locator.JBoVXlr', 'get_ServiceLocator_JBoVXlrService.php', true],
    'App\\Controller\\UtilisateurController::ajoutcompte' => ['privates', '.service_locator.k22NER8', 'get_ServiceLocator_K22NER8Service.php', true],
    'App\\Controller\\UtilisateurController::ajoutprofil' => ['privates', '.service_locator.k22NER8', 'get_ServiceLocator_K22NER8Service.php', true],
    'App\\Controller\\UtilisateurController::register' => ['privates', '.service_locator.JBoVXlr', 'get_ServiceLocator_JBoVXlrService.php', true],
    'App\\Controller\\AjoutController:depot' => ['privates', '.service_locator.ZIsCxOI', 'get_ServiceLocator_ZIsCxOIService.php', true],
    'App\\Controller\\AjoutController:listParten' => ['privates', '.service_locator.eIEYWuf', 'get_ServiceLocator_EIEYWufService.php', true],
    'App\\Controller\\AjoutController:partuser' => ['privates', '.service_locator.H3qnu8f', 'get_ServiceLocator_H3qnu8fService.php', true],
    'App\\Controller\\AjoutController:userBloquer' => ['privates', '.service_locator.U2OyWts', 'get_ServiceLocator_U2OyWtsService.php', true],
    'App\\Controller\\UserController:new' => ['privates', '.service_locator.JBoVXlr', 'get_ServiceLocator_JBoVXlrService.php', true],
    'App\\Controller\\UtilisateurController:ajoutcompte' => ['privates', '.service_locator.k22NER8', 'get_ServiceLocator_K22NER8Service.php', true],
    'App\\Controller\\UtilisateurController:ajoutprofil' => ['privates', '.service_locator.k22NER8', 'get_ServiceLocator_K22NER8Service.php', true],
    'App\\Controller\\UtilisateurController:register' => ['privates', '.service_locator.JBoVXlr', 'get_ServiceLocator_JBoVXlrService.php', true],
], [
    'App\\Controller\\AjoutController::depot' => '?',
    'App\\Controller\\AjoutController::listParten' => '?',
    'App\\Controller\\AjoutController::partuser' => '?',
    'App\\Controller\\AjoutController::userBloquer' => '?',
    'App\\Controller\\UserController::new' => '?',
    'App\\Controller\\UtilisateurController::ajoutcompte' => '?',
    'App\\Controller\\UtilisateurController::ajoutprofil' => '?',
    'App\\Controller\\UtilisateurController::register' => '?',
    'App\\Controller\\AjoutController:depot' => '?',
    'App\\Controller\\AjoutController:listParten' => '?',
    'App\\Controller\\AjoutController:partuser' => '?',
    'App\\Controller\\AjoutController:userBloquer' => '?',
    'App\\Controller\\UserController:new' => '?',
    'App\\Controller\\UtilisateurController:ajoutcompte' => '?',
    'App\\Controller\\UtilisateurController:ajoutprofil' => '?',
    'App\\Controller\\UtilisateurController:register' => '?',
]);
