<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOghjtKS\srcApp_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOghjtKS/srcApp_KernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerOghjtKS.legacy');

    return;
}

if (!\class_exists(srcApp_KernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerOghjtKS\srcApp_KernelTestDebugContainer::class, srcApp_KernelTestDebugContainer::class, false);
}

return new \ContainerOghjtKS\srcApp_KernelTestDebugContainer([
    'container.build_hash' => 'OghjtKS',
    'container.build_id' => '3d7d06d6',
    'container.build_time' => 1565103718,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOghjtKS');
