<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container7XkqpJd\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container7XkqpJd/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container7XkqpJd.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container7XkqpJd\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \Container7XkqpJd\srcApp_KernelDevDebugContainer([
    'container.build_hash' => '7XkqpJd',
    'container.build_id' => 'ae4debe7',
    'container.build_time' => 1565102872,
], __DIR__.\DIRECTORY_SEPARATOR.'Container7XkqpJd');
