<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYyFY3hx\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYyFY3hx/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerYyFY3hx.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerYyFY3hx\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerYyFY3hx\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'YyFY3hx',
    'container.build_id' => '06fc69fe',
    'container.build_time' => 1565287900,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerYyFY3hx');
